<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Version>1.$([System.DateTime]::Now.ToString("yyMM")).$([System.DateTime]::Now.ToString("dd")).$([System.DateTime]::Now.ToString("HH"))</Version>
	  <FileVersion>$(Version)</FileVersion>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <InformationalVersion>$(Version)</InformationalVersion>
	  <ApplicationIcon>san-vicente-y-las-granadinas-_1_.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="san-vicente-y-las-granadinas-_1_.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrmComun\FrmComun.csproj" />
    <ProjectReference Include="..\SQLSIVEV\SQLSIVEV.csproj" />
  </ItemGroup>

</Project>