<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Version>7.$([System.DateTime]::Now.ToString("yy")).$([System.DateTime]::Now.ToString("MM")).$([System.DateTime]::Now.ToString("ddHH"))</Version>
	  <FileVersion>$(Version)</FileVersion>
	  <AssemblyVersion>7.0.0.0</AssemblyVersion>
	  <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fontawesome.sharp" Version="6.6.0" />
  </ItemGroup>
	

  <ItemGroup>
    <ProjectReference Include="..\FrmComun\FrmComun.csproj" />
    <ProjectReference Include="..\SQLSIVEV\SQLSIVEV.csproj" />
  </ItemGroup>

</Project>